apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: snssqs
  description: This is an example of how to use AWS SNS and SQS to publish messages to a topic(SNS) and consume them from a queue(SQS) using NodeJS and the aws-sdk.
  labels:
    version: 0.1.0
    category: integration
  tags:
    - nodejs
    - aws
    - sqs
    - sns
  annotations:
    github.com/project-slug: marllonfernandes/snssqs
  links:
    - url: https://docs.aws.amazon.com/pt_br/sns/latest/dg/sns-send-message-to-sqs-cross-account.html
      title: Documentation
      icon: description
spec:
  type: openapi
  lifecycle: experimental
  owner: ti-team-servicos
  system: snssqs
  definition:
    $text: https://github.com/marllonfernandes/snssqs/blob/793221ebf946b0872e6cb9954f5c8e95fee225de/openapi.yaml
