openapi: 3.0.3
info:
  title: SQS/SNS AWS - OpenAPI 3.0
  description: Service integration SQS with SNS
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://host.swagger.io/api/v3
tags:
  - name: sqs
    description: Everything about SQS
    externalDocs:
      description: Find out more
      url: http://swagger.io
  - name: sns
    description: Everything about SNS
    externalDocs:
      description: Find out more about
      url: http://swagger.io
paths:
  /sqs:
    get:
      tags:
        - sqs
      summary: Finds SQS
      description: Finds SQS
      operationId: findSqs
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items: {}
            application/xml:
              schema:
                type: array
                items: {}
        '400':
          description: Invalid status value
  /sns:
    get:
      tags:
        - sns
      summary: Finds SNS
      description: Finds SNS
      operationId: findSns
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items: {}
            application/xml:
              schema:
                type: array
                items: {}
        '400':
          description: Invalid status value
